(defpackage #:llambda/chatbot
  (:use #:cl)
  (:export #:*llambda-max-tokens*
           #:*llambda-repetition-penalty*
           #:*llambda-top-k*
           #:llambda-chat-backend-handler
           #:register-llambda-chat-backend))

(in-package #:llambda/chatbot)

(defparameter *llambda-max-tokens* 256
  "Maximum number of tokens generated by one chatbot turn.")

(defparameter *llambda-top-k* 40
  "Top-k sampling limit used by llambda chatbot turns.")

(defparameter *llambda-repetition-penalty* 1.15f0
  "Repetition penalty used by llambda chatbot turns.")

(defparameter *llambda-generate-response-function*
  #'llambda:generate-gguf-response
  "Function used to run one GGUF generation. Bind this only for testing.")

(defun llambda-message-value (message key)
  "Returns string-keyed KEY from provider-neutral MESSAGE."
  (cdr (assoc key message :test #'string=)))

(defun llambda-message-role-label (role)
  "Returns transcript label for provider-neutral ROLE."
  (cond
    ((string-equal role "user") "User")
    ((or (string-equal role "assistant")
         (string-equal role "model"))
     "Assistant")
    ((string-equal role "system") "System")
    (t (error "Unsupported llambda chat message role: ~S" role))))

(defun llambda-chat-prompt (bot conversation input)
  "Builds a complete provider-neutral transcript ending in INPUT."
  (unless (stringp input)
    (error "llambda backend requires string input, got ~S." input))
  (with-output-to-string (stream)
    (let ((system-instruction
            (chatbot::system-instruction-text
             (chatbot::chatbot-system-instruction bot))))
      (when system-instruction
        (format stream "System: ~A~%~%" system-instruction)))
    (dolist (message (chatbot::conversation-messages conversation))
      (let ((role (llambda-message-value message "role"))
            (content (llambda-message-value message "content")))
        (unless (stringp content)
          (error "llambda backend supports only text conversation content, got ~S."
                 content))
        (format stream "~A: ~A~%~%"
                (llambda-message-role-label role)
                content)))
    (format stream "User: ~A~%~%Assistant:" input)))

(defun llambda-generation-option (config key default)
  "Returns CONFIG value for KEY, or DEFAULT when absent."
  (or (getf config key) default))

(defun llambda-chat-backend-handler
    (input &key bot conversation callback file-attachments
                effective-model effective-generation-config)
  "Runs one registered :LLAMBDA backend turn against a local GGUF model."
  (when file-attachments
    (error "llambda backend does not support file attachments."))
  (let* ((model-path (or effective-model (chatbot::chatbot-model bot)))
         (history (chatbot::stateless-history-messages
                   (chatbot::conversation-messages conversation)
                   input))
         (prompt (llambda-chat-prompt bot conversation input))
         (temperature
           (llambda-generation-option effective-generation-config
                                      :temperature
                                      1.0f0))
         (top-p
           (llambda-generation-option effective-generation-config
                                      :top-p
                                      0.95f0))
         (top-k
           (llambda-generation-option effective-generation-config
                                      :top-k
                                      *llambda-top-k*)))
    (unless (and (stringp model-path) (string/= model-path ""))
      (error "llambda backend model must be a GGUF pathname string."))
    (multiple-value-bind (header kv-pairs generated-ids text last-logits)
        (funcall *llambda-generate-response-function*
                 model-path
                 :prompt prompt
                 :repetition-penalty *llambda-repetition-penalty*
                 :top-k top-k
                 :top-p (coerce top-p 'single-float)
                 :temperature (coerce temperature 'single-float)
                 :max-tokens *llambda-max-tokens*
                 :callback callback
                 :stream (make-broadcast-stream))
      (declare (ignore header kv-pairs generated-ids last-logits))
      (chatbot::emit-chat-response-text text)
      (chatbot::make-chat-turn-result
       text
       :messages
       (chatbot::update-conversation-stateless-history
        history
        (list (cons "role" "assistant")
              (cons "content" text)))))))

(defun register-llambda-chat-backend ()
  "Registers native llambda inference under chatbot backend :LLAMBDA."
  (chatbot:register-chat-backend :llambda #'llambda-chat-backend-handler))

(register-llambda-chat-backend)
