(defpackage #:llambda
  (:use #:cl)
  (:import-from #:sb-simd-avx2
                #:f32.8
                #:f32.8*
                #:f32.8-
                #:f32.8-aref
                #:f32.8-horizontal+
                #:make-f32.8)
  (:import-from #:sb-simd-fma
                #:f32.8-fmadd)
  (:export #:aligned-tensor-mapping-closed-p
           #:aligned-tensor-mapping-p
           #:aligned-tensor-mapping-tensors
           #:aligned-tensor-view-dot-product
           #:aligned-tensor-view-element-type
           #:aligned-tensor-view-length
           #:aligned-tensor-view-p
           #:aligned-tensor-view-ref
           #:architecture-descriptor-for-kv-pairs
           #:architecture-descriptor-name
           #:architecture-descriptor-p
           #:architecture-descriptor-tokenizer-policy
           #:call-with-aligned-tensor-mapping
           #:call-with-file
           #:call-with-mapped-file
           #:apply-repetition-penalty
           #:apply-top-k
           #:apply-top-p
           #:apply-temperature
           #:apply-rope
           #:apply-silu
           #:benchmark-gguf-projection-backends
           #:close-aligned-tensor-mapping
           #:close-gemv-runtime
           #:close-handle
           #:close-model
           #:create-file
           #:dequantize-q4-k-m
           #:dequantize-q6-k
           #:detokenize-token-id
           #:detokenize-token-ids
           #:decode-next-token
           #:default-gpu-cache-directory
           #:default-npu-cache-directory
           #:enable-model-gpu-projections
           #:enable-model-gpu-layer-projections
           #:enable-model-npu-projections
           #:enable-model-npu-layer-projections
           #:ensure-model-gpu-projection
           #:ensure-model-npu-projection
           #:evaluate-prompt
           #:export-model-gpu-projection
           #:export-model-npu-projection
           #:generate-from-prompt
           #:generate-gguf-response
           #:generate-token-loop
           #:hello-message
           #:find-gguf-tensor-info
           #:find-architecture-descriptor
           #:load-gemma4-model
           #:load-architecture-model
           #:load-gpu-backend
           #:load-llama-model
           #:load-npu-backend
           #:load-qwen2-model
           #:load-gguf-tensor
           #:load-gguf-tensor-by-name
           #:make-gemma4-step-function
           #:make-architecture-step-function
           #:make-llama-step-function
           #:make-qwen2-step-function
           #:model-gpu-layer-projection-names
           #:model-npu-layer-projection-names
           #:gpu-backend-available-p
           #:gpu-backend-runtime-version
           #:npu-backend-available-p
           #:npu-backend-runtime-version
           #:register-model-gpu-projection
           #:register-model-npu-projection
           #:register-architecture
           #:clear-model-gpu-projections
           #:clear-model-npu-projections
           #:unregister-model-gpu-projection
           #:unregister-model-npu-projection
           #:map-view-of-file
           #:main
           #:print-gguf-file
           #:print-gguf-floating-point-tables
           #:copy-tensors-to-aligned-temp-file
           #:map-gguf-tensors-to-aligned-arrays
           #:forged-dot-product
           #:read-gguf-header
           #:read-gguf-kv-pairs
           #:read-gguf-tensor-infos
           #:rms-norm
           #:sample-from-probabilities
           #:sample-token-id-from-logits
           #:silu
           #:softmax
           #:supported-architecture-names
           #:test-gemma4-e2b-it-response
           #:test-gguf-file-response
           #:test-llm-response
           #:tokenize-prompt
           #:unmap-view-of-file
           #:vector-matrix-multiply
           #:with-aligned-tensor-mapping
           #:with-file-handle
           #:with-mapped-file))
