(defpackage #:llambda
  (:use #:cl)
  (:import-from #:sb-simd-avx2
                #:f32.8
                #:f32.8*
                #:f32.8-
                #:f32.8-aref
                #:f32.8-horizontal+
                #:make-f32.8)
  (:import-from #:sb-simd-fma
                #:f32.8-fmadd)
  (:export #:call-with-file
           #:call-with-mapped-file
           #:apply-repetition-penalty
           #:apply-top-k
           #:apply-top-p
           #:apply-temperature
           #:apply-rope
           #:apply-silu
           #:close-handle
           #:create-file
           #:dequantize-q4-k-m
           #:dequantize-q6-k
           #:detokenize-token-id
           #:detokenize-token-ids
           #:decode-next-token
           #:default-npu-cache-directory
           #:enable-model-npu-projections
           #:enable-model-npu-layer-projections
           #:ensure-model-npu-projection
           #:evaluate-prompt
           #:export-model-npu-projection
           #:generate-from-prompt
           #:generate-gguf-response
           #:generate-token-loop
           #:hello-message
           #:find-gguf-tensor-info
           #:load-gemma4-model
           #:load-llama-model
           #:load-npu-backend
           #:load-qwen2-model
           #:load-gguf-tensor
           #:load-gguf-tensor-by-name
           #:make-gemma4-step-function
           #:make-llama-step-function
           #:make-qwen2-step-function
           #:model-npu-layer-projection-names
           #:npu-backend-available-p
           #:npu-backend-runtime-version
           #:register-model-npu-projection
           #:clear-model-npu-projections
           #:unregister-model-npu-projection
           #:map-view-of-file
           #:main
           #:print-gguf-file
           #:print-gguf-floating-point-tables
           #:copy-tensors-to-aligned-temp-file
           #:map-gguf-tensors-to-aligned-arrays
           #:forged-dot-product
           #:read-gguf-header
           #:read-gguf-kv-pairs
           #:read-gguf-tensor-infos
           #:rms-norm
           #:sample-from-probabilities
           #:sample-token-id-from-logits
           #:silu
           #:softmax
           #:test-gemma4-e2b-it-response
           #:test-gguf-file-response
           #:test-llm-response
           #:tokenize-prompt
           #:unmap-view-of-file
           #:vector-matrix-multiply
           #:with-file-handle
           #:with-mapped-file))
